apiVersion: v1
kind: Service
metadata:
  labels:
    app: migration-planner
  name: migration-planner-agent
spec:
  ports:
    - name: migration-planner-agent
      port: 7443
      protocol: TCP
      targetPort: 7443
  selector:
    app: migration-planner
  type: LoadBalancer
status:
  loadBalancer: {}
