apiVersion: v1
kind: Service
metadata:
  labels:
    app: migration-planner
  name: migration-planner
spec:
  ports:
    - name: migration-planner
      port: 3443
      protocol: TCP
      targetPort: 3443
  selector:
    app: migration-planner
  type: LoadBalancer
status:
  loadBalancer: {}
