apiVersion: v1
kind: Secret
metadata:
  name: migration-planner-rds
  labels:
    app: postgres
type: Opaque
stringData:
  config.yaml: |
    database:
      hostname: postgres
      name: planner
      password: adminpass
      port: 5432
      type: pgsql
      user: admin
    service:
      address: :3443
      agentEndpointAddress: :7443
      imageEndpointAddress: :11443
      baseAgentEndpointUrl: https://localhost:7443
      baseImageEndpointUrl: https://localhost:11443
      baseUrl: https://localhost:3443
      logLevel: debug
      auth:
        type: local
        localPrivateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3hhTUd1ODIxb2xraHEKVW1yRk1JL3BjRmhueHJENFo4OFFWbUxIcDZqVFUyV3AzVEc2Qmw3UlhmMjVJOXVUOWUxa3Njb3pjeDg0QWZLTgpKSVV2clNsT2dwT2ZyUDY2YlhyRWVFWWJhMmNaVHJmOC84SXo1Q0ZQVTdRdW5JdE5Vd2VmelNZbEJPRnNTd1loCjNOZjNQQzQzUHVIM3AyNHdlckxRRXZLTGxQWmRKQmFPVzl6b0tHV3Q2Y3dhb2VYcldxYTM3b0lldVlXOEtIb0sKQjYveHVyeVlyeE03MjhQMjkyb3R6NkpFd3MyMVBqTnEwbkpZc0RFMVdUaE9uZkN3azJ2OHQwVXM2QUtTY0kvLwo0ck1sWEJaK21Rc3JpdXFiYWxpSGFhMExVSG1MRUJ2bFdJZzFFZmtGQzJQbGdmU1lsbnB5N2NRS2x1aUdKek5uCmJzT3ZSNldaQWdNQkFBRUNnZ0VBRGRiQ1h3dVpvZ0l4R1d3ZTdJMW1lSHI5Um5FYkhuRjRsMGxwMExHOUsyankKd2Y2aGNhV3NFVkJ2NlppSXVTREN1U3RlUHNldzdIMUlacWF0NWdOdnVMSmFZaWNNUXM0bCtMdjZHZ3IxZ3FXZgptQko2VzNKay84dGpmNHhTR0lETTFEUWNVT0J4MWpEL0JEYTJPUkMrZVN4RVU3MkJqTElSajBZZkdmRFBqQUhTCmxORjE1Q2pjSmZnVzFRSUNhbmFKenZwd0h4Y2t2K1h5aHZDY1VRQm10M3NPNWQrZ09UQ3JOS2dhMVhGU1ZIcWEKRzNqZ1NOalpxZmcwSVJFcis0YmNnVjIwdUN4THgzTW0yMjhGdDRTTjlDd0c0SXdlNVhnT05tZ0VHeUJ2TWZZMQovZEtzRmZmREdiTFNlMFBCeit4c3REaVRqTG03RUZYWnhVcGl2cHZaNFFLQmdRRGtzMWdPcmkxS1owVnJiZGovClFVb2dESnBTK05pZmhXdTZIZ0k2bVJZNHN5eGFoWFJFY3luUXpyT3RIemppNGRjMkFJQWxUeDZTcEFKTTI3eG4KMDZ4ZlZkckhOMUk4bW5wcGg3Z3BIWUZ0V3hOSk5oK2dIcWc2SmNxRjJTTzd5dEdkSDhGSGVNOWM5ZmErVnpxegpKd3RrMXlpNGpOdHNxQ3dWaVVlaDBrWFJhUUtCZ1FER2xndStuekpQN1R0OXh0SFJmd09oWlhrby8rN05wa2luCkZ3ckVIMVVmSXkxL3BGMEFtMkczVFBEeFpxMzRnYWd2TEtkcXU5SEVGV0l1ako0T0ZHRysvRUZISHE4Wi92bkEKdkhOWGc4UUF1UFpRSlNxZThyMUFrbzh3Mm4xeWdUZEdMQVp6Wkg5Wkh6OGFHbFFTT2J3RzhRV3hFNkg3Rk5TcQphVFNkQ1p0OHNRS0JnUUNHN2pFRDZFdWNYRFdlM2w1cXF4Q2F2QlRJNHp5YlVWSnZxb2pTSGNQNGkrMmRNcU9ZClJ3SGl5akZEOE9uVklqMmhCTWFXUEluakpwU2MxLy9lbWdwVzdRWjVCdkNrQk5nNEx2UytmVVFCU3Z5ajh5VFIKaVlUaldheVZMN2xmY0pnZlJiNzQ5aFFSMnFSTFJKZkRYMFBmcVBuRGVJZDFJZnR3Y1dBcjN5MkdFUUtCZ0ZEZgpELzljRTRBckt6d0llSy9wR3RCaVk1b0h4L2RselZhR2NyTDEwNU52bnZySk03cW9qSDI2VHJEd1VNN1A5bTduCnIzSXU5TGoyd0ZvV2w5TkNCNkJnV0RFZlZNMndZWU5VKzEvYllEbXZHVmdBR3NCS09Eb1F0VkYrMlBHRm43M3EKOWVHT1BySkxvRVlBRE5helBsaFJWVEVNdnIxaWVVekF0VlZ5Y1NpeEFvR0JBTTdmUVdVdzJrRW83aDAvdEdBZwowYkpVSkNqSU9QMTdTT3ZnTjFjUTZzaTAwVzFhT3c4bnJyN2hnTDVEMnM5TTA1b2JXYU5xSDkwYmtpWnppTVJNCmh4M2g5MGZDbUNiYlBRV1U5TDJldm1iY3RxRm1mdHM0UWdvc2VCMHB6QWxEN2N2cjNCQXlXWENmUFYzbDdST2kKbzdyVW9YaEo5eVBWMlFkMDhaNjBtS000Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  db.host: "postgres"
  db.name: "planner"
  db.password: "adminpass"
  db.port: "5432"
  db.user: "admin"
