apiVersion: v1
kind: Secret
metadata:
  name: migration-planner-rds
  labels:
    app: postgres
type: Opaque
stringData:
  config.yaml: |
    database:
      hostname: postgres
      name: planner
      password: adminpass
      port: 5432
      type: pgsql
      user: admin
    service:
      address: :3443
      agentEndpointAddress: :7443
      baseAgentEndpointUrl: https://localhost:7443
      baseUrl: https://localhost:3443
      logLevel: debug
  db.host: "postgres"
  db.name: "planner"
  db.password: "adminpass"
  db.port: "5432"
  db.user: "admin"
