---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: migration-planner-private-key-secret
parameters:
  - name: E2E_PRIVATE_KEY_BASE64
    description: Base64-encoded content of the private key file.
    displayName: Private Key Base64 Content
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: migration-planner-private-key-secret
    type: Opaque
    data:
      private-key: ${E2E_PRIVATE_KEY_BASE64}
