openapi: 3.0.1
info:
  title: Migration Planner API
  version: undefined
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /
paths:
  /api/v1/sources:
    get:
      tags:
        - source
      description: list sources
      operationId: listSources
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceList'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - source
      description: create a source
      operationId: createSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceCreate'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - source
      description: delete a collection of sources
      operationId: deleteSources
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/sources/{id}:
    get:
      tags:
        - source
      description: read the specified source
      operationId: readSource
      parameters:
        - name: id
          in: path
          description: ID of the source
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - source
      description: delete a source
      operationId: deleteSource
      parameters:
        - name: id
          in: path
          description: ID of the source
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Source:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [not-connected, waiting-for-credentials, error, gathering-initial-inventory, up-to-date]
        statusInfo:
          type: string
        inventory:
          $ref: '#/components/schemas/Inventory'
        credentialUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - status
        - statusInfo
        - inventory
        - credentialUrl
        - createdAt
        - updatedAt

    SourceCreate:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    SourceList:
      type: array
      items:
        $ref: '#/components/schemas/Source'

    Error:
      properties:
        message:
          type: string
          description: Error message
      required:
        - message

    Status:
      type: object
      properties:
        message:
          type: string
          description: A human-readable description of the status of this operation.
        reason:
          type: string
          description: A machine-readable description of why this operation is in the "Failure" status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.
        status:
          type: string
          description: 'Status of the operation. One of: "Success" or "Failure". More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
      description: Status is a return value for calls that don't return other objects.

    Inventory:
      type: object
      required:
      - vms
      - infra
      properties:
        vms:
          type: object
          $ref: '#/components/schemas/VMs'
        infra:
          type: object
          $ref: '#/components/schemas/Infra'

    VMs:
      type: object
      required:
      - total
      - totalMigratable
      - cpuCores
      - ramGB
      - diskGB
      - os
      - notMigratableReasons
      properties:
        total:
          type: integer
        totalMigratable:
          type: integer
        cpuCores:
          type: object
          $ref: '#/components/schemas/Histogram'
        ramGB:
          type: object
          $ref: '#/components/schemas/Histogram'
        diskGB:
          type: object
          $ref: '#/components/schemas/Histogram'
        os:
          type: object
          additionalProperties:
            type: integer
        notMigratableReasons:
          type: object
          additionalProperties:
            type: integer

    Infra:
      type: object
      required:
      - folders
      - networks
      - datastores
      properties:
        folders:
          type: object
          additionalProperties:
            type: object
            properties:
              numVMs:
                type: integer
              folderIDs:
                type: array
                items:
                  type: string
        networks:
          type: array
          items:
            type: object
            required:
              - type
              - vlanID
            properties:
              type:
                type: string
                enum: [standard, distributed]
              vlanID:
                type: integer
        datastores:
          type: array
          items:
            type: object
            required:
              - type
              - totalCapacityGB
              - freeCapacityGB
            properties:
              type:
                type: string
              totalCapacityGB:
                type: integer
              freeCapacityGB:
                type: integer

    Histogram:
      type: object
      required:
      - minValue
      - step
      - data
      properties:
        minValue:
          type: integer
        step:
          type: integer
        data:
          type: array
          items:
            type: integer