// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW/bOPL/KgT3D/zvANlOdnvAwcC+SNMnY/sQJG33xTYoaHFscUORWpJy4iv83Q8k",
	"JUuyKFlp42721u/SkJznGf5mxPQLjmWaSQHCaDz9gnWcQErcj2dLEMb+kCmZgTIM3K9jBcQAPXNLC6lS",
	"YvAUU2JgZFgKOMJmnQGeYm0UE0u8iewRCsIwwj8obo+1djDaoJbnjIYIaUNM7qQAkad4+hsW0oxiKQTE",
	"BuyRW8IME8vRQqpRxVbjCINSUuEIL4lJwBIcMcHs4oiJFQgj1RpHOM9GRo6sNjjCWuYqhtFSCsDXneLM",
	"xEIGlcozel9LrUBpJkWA3CbCCv7ImQJq9Xb2KczREGTX2lHNYXWRKl6VZnL+O8TGyuF8f6Hk3bodAIkx",
	"WeHHlInXIJYmwdPTCIucczLngKdG5bCrXYTvRpJkbBRLCksQI7gziowMWTqqK8KZM/sUy5QZwXiUKx5p",
	"Q5TRQppbZpKfLWvtbOF++s5S7Igg5NZAh5UgJXc/n56cnOCNZdv2ldagdfpQyTowFaukmX7B/6dggaf4",
	"h0lVTCZFJZnMthutzUgKwVzxqTZ7NoB3KBMc3Wao17N6S/26134vpErbNixlbjr5ATUohB8o5GumnTeZ",
	"gVTvM34tNqrQIUoR541nxBBtpIK20pTpmxkNumqhAM5JRmJm1i+f1rYwYWAJyu5JiKK3RMFZHAMHZZ3y",
	"Rq7qrp9LyYEIuzmVFMLXQqakkbHk791CYIORhvB9wpiu0ysQVKr9xdattpm1TLGlGJX267bEjnKlFUK+",
	"f+5urpaLUtCaLJ1mFHSsWGbc1eH3o3J5X/SV+643EX7FtJFLRQJZQIkhjbDrsnMVXikTHwnPIbxbG8hC",
	"K7vilUSKE5GXJGSnV1IHSmB3dA11/9ap3S6aiYUigfLLc21A6QtQNtdiEAbUPa1IyyTVg7O+yusAvURq",
	"cyFvQV0ZYjxRQimzsUP4RUP8TuEqxS214YI5D3XIZI107u11TwsJMLdS3QwX460/EKLlc7xwWwd7u6Vy",
	"Z9+uV6V12uur9GsV3i1OFaNd8duGbbu/Zr5GrIWjvHbnNyOdlQnQDwXsJqt8lQl9+z+e+23eXHt3v9Ht",
	"1C0YeQJRIWZIt9dk7stEU68bWLcLxHAIV8oScUfeirfaKYnfTnNHZytyySak6Ru2VMSm+0zrPHD1kwae",
	"bDdzMm+s1OKUhQEDL03bX2b9tqjOv+S2X43hyb+jfqAGlOWhfQeubA8QJ0EtO6FtCT/KllUbIihR1KME",
	"o9g8973rlnyEc6HzLJPKLoQ6zxUnIgjPwsjFyRYy4pXDnIEYKHv/XnC5LHDlY+syXCQNjwif+qGLpcul",
	"UlwoSJluXJM1RHvvzn9gT1Nv32sydHv23B0OABP744LFxMB5QpjYW1uL8kPPdw8+lLnv1xZDmpl1RNkK",
	"oq3dNjWPDdLFm+itPeJ7jbv1oJD3bb+FsDq5yOecxb/AejjXq1fVoWAr2O3Oe/V+RW4H4tqvfMjoMTa6",
	"dHmXeUD8SGKkHQ/bSWiz9/O/R0wjghSYXAnkkABaSIViwrlGJiEGUSn+35Q7pElAIU9cj31rOqTRPENJ",
	"nhIxUkAomXNAtWUkF8gkgPxo0v+LaWTputt3HCr3Coj2089dRimJEyagk9Vtst5hYG3AhJPhE35BGM8V",
	"fMKFPGM0KwTy1mEaubCx25X7p5CICV+6LTGyIswN9cboDF06MVHMiWILBhoRgV69f39RKmvDFM1za2Ww",
	"lAySK1CKUUDMjPsH20F3FrasjIfeCUByMUWf8FUex6D1J4ykqms6Rm+kVUUs5BS5qeV0MlkyM775tx4z",
	"aeMvzQUz60kshUchUukJhRXwiWbLEVFxwgzEJlcw8dnnLlkmhR6n9AedQTwigo62Y+j2pdaKW190ehoJ",
	"hzxmh0MHuzdtbUpYsg7V37IVaTc+dNCwPkjzzSX4od9TBeSGylsRmLbXRzK9vfV2Y9l99jSmL6TyONjP",
	"qYft+5WZ5FeiBBNL3X/mrTT95HcMVClZih6Uc69QXRKEra8Dd1+Wn5ejlv5es+26jZ/6nZf90Vee91PM",
	"rziclo1N3UcP1BIJFn+LXqLuDV89H1I6ec8pFoVMgYUpdOcTTRUdcvtZr4tsn8jF6VABzB5s9KZI+tWx",
	"sq8+DCoOwytDaGSF26yiKv9K9bY5UU8u5/GmKTtiLJQVwWLQiWEP/nXPwm0/uOoDn98wL6owsQ+EzxYI",
	"RykTP5+Wnxab7Bvo8+D6a518vilgbqg1e4hJWb/iVa7vXAbdk65qOhPo/3eiPS5iNjTRqdUFBZotBdBR",
	"rgJzSLjLmAL9mZjA9x675mGqYamH+hYufrh8jYy8AYe1h41lCt5N+hcKRl42R9KSt3WES0KZWHqU7wyM",
	"KNOxhbprxFKyhPHeQYfl17bGxmE77xLOYhAaqg+x+CwjcQLox/EJLgTGJby9vb0dE7c8lmo5Kc7qyevZ",
	"+fO3V89HP45PxolJfYfJjA3iao6ILjgRAhQ6u5jVnkdMcS4oLJiwbWSEZQaCZAxP8U/jk/GpLUPEJM5H",
	"FiRPVqeTaoDpfr2EgM9sJ4/qGx3l4p6jxYazxroCnUlRzJx+PDnxISpMMakjWcZt3WJSTH4vuih/Cwz/",
	"SOzmC878TWnf/WJVf3Jy+mA8/TfNAKsPguQmkYr9x9v7Xw+oaCfTmcX2gnAExY4I+3LyW30afe2ubx3w",
	"ph+z2TawMbxuetRvOqtvsKkA2jyVdH0Ab7rnDDufB2zN3rRi6fQA3EN29iagPpi+g1+fEoouvY2PAWwD",
	"eBOFqtTkC6MbH9UcTGDQ88z9fk98+02N+M6IIin4j6S/7RKdPSvnGg2iFnO5mlqOwKd+HN6M4ahmsX2v",
	"ba6/S+3sq5t/k1B/cvLT4Zm+kGrOKAXhOT45PMe30ryQuXiM11EQW7wE40FZBjFbMKB9WfsSzDFljyl7",
	"TNnvfgH7nkn33bu0uHdRLDmHuPzYUZ4M38BX29WDpVDx9enYKdT97L3SXZZdy9flOrtYOa63CLvPNZKj",
	"24QYWIHv9SksSM4NUpBJZZBOZM4pmgMilAJFRrpdCnTOtxX7jxzcd4+yZIuY5xQ+F6RwvV63RhyHLNC1",
	"b93HCOuIsP4+tAizjhb0qlw8RPvZeHfynZvP8sXDsfF8VNHavvMGN5xdgVy/6YaD1i2xvxZg7Q7rI1g9",
	"gtVvYngP+NLuKjty8yWYY2IeE/OYmAfDfnkgPf3Dqq6c9KuPLS0PhT6Ll62D0Of3qAZenm3BPFaGY2X4",
	"6spwBcr2/M/vDbcn7pO8e1IIhLYLyCsg1GX9u49n/vN9q4rYLbNipb+E0D/vZu+5iIekx6Bw3h9+e8Pl",
	"vu71Htnj3fLtSC+A2/oXrRhBHy5fdyO4Z8UzD7+p1+X+AHKe+muhuObLm1BNc+9otm9eagny96rkT/6k",
	"zmRv6Ddek/eAo/pj7xA+mtXW/2ch0q6qjxQl1Zx1xEtHvPQn4CW1MlL6v13rKyrljBLN1yjPykeRRKDL",
	"j+/tebRgHBBlCmLDQ5XHHrn0vF4w/hdoz9KcG5YRZSaWzKj8n0Eq6s2nq1b/tvXeJ9C00D+e38XA/1l/",
	"qjpngrhi3P+I1DEIvyJ92LrW+Wdxe//wKZCDVmcfL7bm+T/iWuScH+vdsd4dvN4lQLhJOlsFv4ziBOKb",
	"UBfIXakZ1n3VRCi4Xjv5tRPUVzj/inuCN9eb/wYAAP//kXQZmpFQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
