// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW2/bOBb+KwRngd0FfEk7XWDhtzS9GdOLkds8tMGAFo8tTihSQx7Z9Rb+7wuSki1b",
	"lOxkk04Xk7ckJM/1O4ffofKNJjrLtQKFlo6+UZukkDH/4+kcFLofcqNzMCjA/zkxwBD4qV+aaZMxpCPK",
	"GUIfRQa0R3GVAx1Ri0aoOV333BEOCgWTV0a6Y40dgu9IKwrBY4IsMiy8FaCKjI4+U6Wxn2ilIEFwR5ZM",
	"oFDz/kyb/latpT0KxmhDe3TOMAUnsC+UcIt9oRagUJsV7dEi76PuO29oj1pdmAT6c62A3rSaM1YzHXWq",
	"yPldI7UAY4VWEXHrHjXwRyEMcOe3j08Zjh1D9qPdqyWsbtJW19YzPf0dEnR2+NxPjP66agIgRczb8ujW",
	"bNui0huJTecaJrxiyCxqA00LuLC3Yx7VMTMAZyxnicDV25e1LUIhzMF4I5nhS2bgNElAgnEB+aAXUNs8",
	"1VoCU25zpjnE3cmNRp1oeekXIhtQI5OHjMG20wtQXJvDSPCrTWWNUGwk9qr4tUdiz7kqCjGkvPZl1UhR",
	"BtayufeMg02MyNHjOuwn1XLvgHPVvpt1j47VzLBIP5KFRTB2AsZBJgGF4A0SCJntCjplxrCV+51XWLM7",
	"B/9mYEZH9KfhtkcOywY53MIzIi/VFid6CeYCGQahjHPhQsDkZMf8VuO2IXbSnHtnwdM7+qYAl9rc7nq2",
	"V08LuxSYpPGqZVkLvEvkVq3YIlOcGR4AhkZMi9CTN+J7tFC2yHNt3EKsoy4kU9HKjoPe2xZD5X4QQnWU",
	"SGmJm9uyRVDXrncuIbH1fSu3myPy963qtUC5CYAmwGpp3kFzLDbjzXXXAIKoSqwL+aEOXbK2tda1//os",
	"bHMnDtfV9QfbiONiEwknoFeaGfPtPZuGbr3r1y2s4j2WyQIOo80drzbHtH4Qc8NccY+tLaCr0pi1YG1W",
	"EqsmUdLFzkoNeLLyrNvUsK1XV1SJPaZOLjzjidhdccGu1AXCuO7dhyIeSQBFHbvdIK02VrE7vrUHEMVa",
	"aVsr1GpiIBN2p6XXSMSdmWCM7Xnt7XSuZkMs0yGzZ/5w5BJ1P85EwhDOUibU3W6CvKJ1B9ERCKCjzjad",
	"FFMpkl9gdRjVrX0+ePVeWDw6uyXEW8F/5WP6yUezpRDGjwfW/cTXRpNKdTQOm8Fol22FvxNhCSMGsDCK",
	"+DZGZtqQhElpCaYMCdfq71jt0G5AIkG4HQQyeAy1OyVpkTHVN8A4m0ogtWWiZwRTIGFSCb8JS5xc3zkH",
	"sQAaYDYMQ/uKMpakQkGrqmW62lPgYiCUt+ELfcOELAx8oaU9AzIuDQrREZZAlqOTAcb/qjQRKmTcCWML",
	"JqRTPCCn5NybSRLJjJgJsIQp8u7yclI5m2gOZFq4KIOThEQvwBjBgQgcdM+50XSWsdwGj3xSQPRsRL7Q",
	"iyJJwNovlGhT93RAPmjniprpEfFj2mg4nAsc3P7bDoR2sMwKJXA1TLQK5E0bO+SwADm0Yt5nJkkFQoKF",
	"gSHLhRu7HTiFVnaQ8Z9sDkmfKd7fTKVHDHkVN2gyEX7UDByrhesP5xAm95cG2C3XSxUZYoVFPTcsUuKO",
	"Pt2RY2dCXe9Ridpui5AfwRY3QsoTgcjFr21HHDsI6httAidxED12368C01+ZUULNbfeZjxq7xe95tg12",
	"ZXrUzoNGtVkQR0GEfiV5cVZNed0ktAmhdZibzyqKds/z4R3gHoezimTWc9QlZ5+V+heYWthC27qPGP2/",
	"TrR682jWJqTLovJ0THD+YEO3Ydm9U3WoPI+qzeMLMzZ10qaq3hb+lXsbSNax7fO7ydFuTFsgFEPnTWfe",
	"d+ty+ygQoc977sUeEGoAMGDFXAHvFyYyCMLXXBiwvzGMvEy5tXC9O1LuKZK7Zq/O3xPUt+A5ynHTTKl7",
	"V/7EQD/Y5kU68Q4wUjMu1DywI48lwoVNHEVYEZGxOQwOzgdOXzMaa89BQ7ylSEBZj7dA4+lpzpIUyPPB",
	"CS0NphUtWC6XA+aXB9rMh+VZO3w/Pnv98eJ1//ngZJBiFmYkgQ7G2xmYTCRTCgw5nYxrr8wjWigOM6GA",
	"eyTkoFgu6Ij+PDgZPHMwY5j6HDlyMVw8G4ZglCxIAkYYZ/g7YSTRUkJSsb/qpFdTNi9OR/SV336xWTVg",
	"c63Kqe35yYm/IrTCctZleS7dSCS0Gv5eEtFQ+QdnjECBfAZ2Lf70i/P+xcmzB9MVHmAjqq4UKzDVRvwn",
	"hPxfD+hgq9Kxo3OKSQLljh5F5trW5/Jrin/KnUOk/twU15o6t7hNXM4MyyC80n3el+P5q5ZkmTKEBYQi",
	"5jBjhXQjjmsexKa6kJxMgTDOgRPUfpcBW0j0L0x0RP8owA9eZcEIlciCw2+lKEfTNrFq9Kybx0TXduj9",
	"kRAWT3WubSTX4R2CsDLfjXSH9Ytq0fU6sPhS89UDR7F8EFnvdlQ0BawbGXz2wLpjIQ328JDC71CvLxkn",
	"5yG6T41p3du/fIbfBF933UCvqhuoBcj1K+dQ4xq/2rySVPt9H3I3Y60NcboP1XonOvAq9R0aU1dT+osg",
	"+sXJz4+v9I02U8E5qKDxxeNr/KjxjS7U9yvarcI78Ii3gKGIckjETABvq823gE+F+VSYT4X5WDQ/LyLl",
	"Gb6vbG5MMjM6I5vvHGQmZLNSw5kfrVgfi5PufIE6ipl+j05xqsin69PwIvHUM556xv17xgUYN5a/vjMR",
	"Hwbwjb7RFBhvtpZ3wLiv/C1Q9zuJ2zIuV7rbCP/z7vyOK/qY8jgKzofhdxAud01vyMiB7Fbvtp3UbpNf",
	"shCMXJ2/b+d2r8on1rCpM+XhAPGZ+v/id7uv3rGe5t+wN+/Nf9lO/uJPmlkOQd8sUOvwL0pHkabpihR5",
	"9eWAKXJ+fenOe/ZEuDCQoFxFaJQ7ch50vQlE6wfnUlkhUeTM4NCJ6Vff5rfSd7/vePbYiN5lCrsR+sfr",
	"rwnIf9a/50yFYv61t/tLi1cQ/9TysCSt9X9uDv5XRYRcOJ8DXtw0HP5DZFZIuXoick9E7rGJXApMYtp6",
	"p4dlkqSQ3MbomvSt5jiaVDOh1Hrj7bfe0NDhwqfOIV3frP8bAAD//1zrtir9NAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
