// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTXPbNhP+Kxy875ESZSe96GY7SatpnHriJjlkdICIlYiYBFhgKY2b4X/vACBFUgQp",
	"ybU7bac3W1jsx7PPfoDfSSyzXAoQqMn8O9FxAhm1f15tQKD5I1cyB4Uc7M+xAorAruzRWqqMIpkTRhEm",
	"yDMgIcHHHMicaFRcbEgZmisMBHKaflKpudaT4KyjrSg48ynSSLGwXoAoMjL/SoTESSyFgBjBXNlRjlxs",
	"JmupJo1ZTUICSklFQrKhmIBROOGCm8MJF1sQKNUjCUmRT1BOTDQkJFoWKobJRgogy0F3FmItvUEVOTsX",
	"qS0ozaXwqCtDouC3gitgJm6LTwVHx5FDtMNWwtouNbaayOTqG8Ro/LC5v7daP9krXh4cSaqDb3Fuas+F",
	"+WTMToOrVtfy34fQG4pUo1QeZBjXDy7qnq9rBXBDcxpzfPzxuiXCBcIGlJFJqGI7quAqjiEFZfJ1K7fQ",
	"El5JmQIVRjiTDPzo50qijGX6qz3wCKBEmh5zBodub0EwqY6Dbk/7xnpQ7DWGNX7DSBwEV6PgS9NbW/W9",
	"FGWgNd3YyBjoWPEcLYWcfFAfh0eCq+WWZUgWYq2op0zSQiMofQfKUCYGgWAd4giZHgOdUKXoo/mf1VzT",
	"nYv/V7Amc/K/qGnhUdW/o4aeHn2J1Hgnd6BMhTullDFuIKDpXcf9QecaiI02E96Ni/TM2ATgTqqHbmQH",
	"9bTVO45x4uWhoNkAvSvm1pNCIxWMKuYIhoqvCjcy9upDUghd5LlU5sDX8LcpFd7K9pPe+uZj5SEIrjoq",
	"pgzgZkQaBo1J/WQS4js/9LIR9ug/9CocoHKfAH2CtdLcYbMPm8V+GveIwOsSG2O+q0OTrKbWxuQ/3zgx",
	"c+N4XX2+1T0ct3skjIKwctMX23u6ct26G9cDPPp7LE0LOM42c70W9lm95RtFTXEvtC5grNKo1qB1Vu19",
	"/T1OFp2TFvHSOrJxV51Y2DZUqz2lTu7tRPb4Xa+qY6lz+2wZPmWDPXE/5W3ujpO0FqyxO721OxL5WulQ",
	"K5TiTkHGdaelt5aIsxdV3zJqrQ9vmy0ffJl2mR3fOG2WFy+XicOoWs+C2rTP9bqB9NsVO2mP9+q8/Qhu",
	"/bxWQB+Y3Im+/oRrlBtFM8/IpEjPHMQZF58P+k1LWiPkJ4yUvZLqhuv2/to202Vkir2TyjUuukrhVLkv",
	"HJMvVAkuNnr8zgeJ4+oPImvArl33+nnUqSEP/Czw9Og4L27qVXB8UvUpVLrl+qbu40+87x4LT7ic1ZOo",
	"naMxPYejy3S5NmwfgWopnqJG/tm1V+5fpENKxjyqbvsU58+2mSuaPTlVx8rzpNo8vTB9qynpmwob+tfh",
	"7SnZ5rbN7z5HXUwHKORj53I07926bF4Onhl7+CXC88qoLZR2ejkLKY9BaIuwG+7kKqdxAsHldGbmq0rJ",
	"nCSIuZ5H0W63m1J7PJVqE1V3dfR+cfP2w/3byeV0Nk0wc6sDR5O4ZjUM7lIqBKjg6m4RTAI77wIQLJdc",
	"tD8WzUkhGKy5AGbByEHQnJM5eTWdTS8M0hQTi0dEcx5tLyKrSkffOSuj5iNPXmD/8e0Gf+CkArkOMAHn",
	"CrGmqhpme9HWZyprWtEM3OPo66HuxZuONm5+M77Wm8vcbTFNllAVEFbfQ09YOcqluwwaryWza0csBVZ7",
	"Kc3zlMfW/eibdh+rGtVHt9bOXlSWjk46l6Ja6S5nsz6av/xsMnQ5uxg6eu1uPYub7juL9axr6pqy4KPD",
	"xdm8eHmbnwQtMJGK/+5Y+nr26uWNvpNqxRkD4Sy+fnmLHyQGa1kIG+MPf0UyF2bRFTQN7kFtQQW1YEiQ",
	"mr7+tXqJLc1PdQNww+WcDqBtqe73b9MJaODUDDQC93xYtDb2Y82g6i57rf+YhuB5KZXd+WIcHegQz+iB",
	"jx//9ZV/SV959zdrK1WZLu1lbaVcXbsVKCLlsvwjAAD//zAPpVjLHAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
