// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYT2/bNhT/KgK3oxQ7aXcxsEOStquxJguatT0UPjDis81GIjXyyW5W+LsPJEVLlijZ",
	"cZNhG3ZKYL7/f39P30gq80IKEKjJ5BvR6RJyav89X4BA80+hZAEKOdifUwUUgZ3bp7lUOUUyIYwiJMhz",
	"IDHBhwLIhGhUXCzIJjYsDARymn1QmWHrUHC2I60sOQsJ0kixtFaAKHMy+UyExCSVQkCKYFjWlCMXi2Qu",
	"VVKr1SQmoJRUJCYLikswAhMuuHlMuFiBQKkeSEzKIkGZGG9ITLQsVQrJQgogs15zpmIug06VBXtspFag",
	"NJciIG4TEwV/lFwBM37b+FTh2DGkHe24kbCmSbWu2jN59wVSNHbY3N9aqR8sS7AOhpIak6+JpAVPUslg",
	"ASKBr6hognRhuVc0407u1q24VJn104V9ekBJHKFkK3yzU0/fL9eJ2uwpiyMk5/Trz2fjsRXdWx9HyyWb",
	"dmkdVlXekka6QoX0iiLVKFWggBjX9y7JnTaYK4BLWtCU48MvFw0SLhAWoAzNkiq2pgrO0xQyUKasr+QK",
	"GsR3UmZAhSHOJYPw5CmURJnK7Hf7ECBAiTTbZwz2ca9AMKn297N97SrrhGIrMfbx649EyzkfhVCaXtvh",
	"2ElRDlrThfWMgU4VL9BWn6OP/HO8xzlPN9vE5C3XKBeK5oGCoEjNX46Q66E4E6oUfbB55eIjzUoIU2uE",
	"IvTSNs8LqThiZ0koTm+lDqzE/uo6NP3bpPanaCrmigbGcFZqBKVvQJleS0EgqEdGkfkm1TuMPyqYkwn5",
	"YVRDhFGFD0Z1XwfkLaXGG7kGZTaIE0oZ46Z2aHazY36vcbXjRtrhhtkM9dhkgnTp4vXICAnAtVT3h5tx",
	"7RhCslyPV2nrUW9I6nQOUb310em+r/KWw0cnoT2sasVtd7qB7pZDI5w7tReueo/NOpXPfUMM5cF1jQlG",
	"3RlD9B8vHZkL317qK91t5UqRExBXZoZ8e0fv3NjY9eseHp5kv2dWvEUNrRH5/TJbPhuTvZqQp1d8oaip",
	"vKnWZQAKUK1B67y6N7r3gyx3XhqFysMAIvOhHR67jixu6vfaQm74pu5urpVec0yXQVsEzXuQRQUa/C2j",
	"kQpGFXO7HRW/K91RsxUfk1LosiikMg+hk2SVUREEVWG8YW0LuXprQV0gU/4oHGoLdzlu4mNuxQMvQd6c",
	"C8MDwBP6sjh8iLsGDa2DvpRKcaMg53pnrjZw6KNPwtDZZ7X333UNG/ozO3zb2SxPny8Tba8aB7hXHTLd",
	"D+fuKmAHXcxBmVfvwV0wFwroPZNr0ZW/bILWQfSxJfT7eWB1v5HKDUZ6l8GhdJ84Lj9RJbhY6GGea4nD",
	"4lsBqp30pgft3GtUnwXh6OsApC3KSw9Gh7dvN3Ubdxdd+o1xJL+7845gzv2ma+booGHT2pGhqcPT7/FL",
	"NLPxHqiW4imtk4/E+QwKBamZWmSCqoRAdcjtR5Q+sUMmV9yhk6J4suNE0fzoWtk3Hw4aDodPhhCIJ11V",
	"cd1/3r1tTzSby2Z8N5Q9NRbqitlgulvzoB/+1WAosG5bDqeV2SEAtT107EJzRmQ8BaFt7N2+J+cFTZcQ",
	"nZ2MzcpVGZmQJWKhJ6PRer0+ofb5RKrFqOLVo3fTy9fXt6+Ts5PxyRJzhyY4mpTWqDi6yagQoKLzm2mU",
	"RHYFRiBYIblofqmdkFIwmHMBzMarAEELTibkxcn45NQkg+LShmxECz5anY6sKD36xtlmVH/sLErsftJx",
	"WCByVJGcR7gEZwqxqqr2Z1vSxjdiq1rRHNyx+rkte/pqRxo3vxlbPZiZOGBTZ8sNBNc/B6CQzcwxg8YL",
	"yR5c0QisoCotioyn1vzRF+2+ntai9wLZHai0qW4fXUhRobyz8bgbzd9+NRk6G5/2Pb10XE9ipvt6Zy3b",
	"VXVBWfTexcXpPH1+nR8ELXEpFf/TVenL8YvnV/pGqjvOGAin8eXza7yWGM1lKayPP/0dyZwa7CtoFt2C",
	"WoGKPGFM3MX+uTrOZuYnPwDc2nnMBNC2VbeQ3EwCGjkxPYPAXRTTBojfNwyq6bKV+q8ZCIHjqfUxxBja",
	"MyGe0IJQffw/V/4jc+XNP2ysVG06s8zaUrm+dhBoRDazzV8BAAD//yaTX2BIIAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
