// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYT2/bNhT/KgK3oxQ7aXcxsEOStquxJguatT0UPjDis81GIjXyyW5W+LsPJEVLlijZ",
	"cZNhG3ZKYL4/v/f/PX0jqcwLKUCgJpNvRKdLyKn993wBAs0/hZIFKORgf04VUAR2bp/mUuUUyYQwipAg",
	"z4HEBB8KIBOiUXGxIJvYsDAQyGn2QWWGrUPB2Y60suQsJEgjxdKiAFHmZPKZCIlJKoWAFMGwrClHLhbJ",
	"XKqkVqtJTEApqUhMFhSXYAQmXHDzmHCxAoFSPZCYlEWCMjHWkJhoWaoUkoUUQGa9cKZiLoNGlQV7rKdW",
	"oDSXIiBuExMFf5RcATN2W/9U7tgB0vZ23AhYE1Ktq7ZM3n2BFA0OG/tbK/WDZQnmwVBQY/I1kbTgSSoZ",
	"LEAk8BUVTZAuLPeKZtzJ3ZoVlyqzdjq3Tw9IiSOUbIVvdvLp++U6UZs9aXGE5Jx+/flsPLaie/PjaLlk",
	"006tw7LKI2mEK5RIryhSjVIFEohxfe+C3CmDuQK4pAVNOT78ctEg4QJhAcrQLKlia6rgPE0hA2XS+kqu",
	"oEF8J2UGVBjiXDIId55CSZSpzH63DwEClEizfWCwj3sFgkm1v57ta1dZxxVbibH3X78nWsZ5L4TC9No2",
	"x06IctCaLqxlDHSqeIE2+xx95J/jPcZ5utkmJm+5RrlQNA8kBEVq/nKEXA/5mVCl6IONKxcfaVZCmFoj",
	"FKGXNjwvpOKIHZKQn95KHRiJ/dl1aPi3Qe0P0VTMFQ204azUCErfgDK1loJAUI/0IvNFqncYf1QwJxPy",
	"w6heEUbVfjCq6zogbyk13sg1KDNBnFDKGDe5Q7ObHfi94GrDjbTDgdkI9WAyTrp0/nqkhwTgWqr7w2Fc",
	"O4aQLFfjVdh61BuSOpxDVG+9d7rvq/xYg9vNqVbUht91bDf8Dfft5Fo4y/0u1sl07gtgyO+uSozxdSUM",
	"0X+8dGTOXXupr3S3dCtFTkBcwQzZ9o7euTaxa9c9PDzJPM+seLsltFri98ts2WwgezUhS6/4QlFT7lOt",
	"y8Dop1qD1nl1X3TvBVnuvDTylIcXhsy7drjNOrK4qd9rC5nhi7g7qVZ6zTFdBrEImvdsEtWS4G8XjVQw",
	"qpib5aj4XemOmK34mJRCl0UhlXkInSCrjIrgEhXeLyy2kKm3dokLRMofgUNl4S7FTXzMbXjg5cebfWG4",
	"AXhCnxaHN21XoKH23xdSKW4U5FzvDLPG3vnoEzB05lnt/XdcA0N/ZIdvORvl6fNFom1V4+D2qkPQfXPu",
	"jgJ20IUclHn1HtzFcqGA3jO5Fl35y+aSOrhtbAn9PB4Y1W+kco2R3mVwKN0njstPVAkuFnqY51risPiW",
	"g2ojPfQgzr2g+hCEva8DK2xRXvrlc3j6dkO3cXfQpZ8YR/K7u+4I5txPumaMDmo2rRkZ6jo8/R67RDMa",
	"74FqKZ4SnXzkXs+gUJCarkUmqEoIZIfcfjTpEzsEueIOnRDFkx0jiuZH58q+/nBQczi8M4SWeNJVFdf1",
	"583b1kSzuGzEd13Zk2OhqpgNhrvVD/rXv3oZCozblsFpBTu0QHkQGzvQHIiMpyC09b2b9+S8oOkSorOT",
	"sRm5KiMTskQs9GQ0Wq/XJ9Q+n0i1GFW8evRuevn6+vZ1cnYyPlli7rYJjiak9VYc3WRUCFDR+c00SiI7",
	"AiMQrJBcNL/MTkgpGMy5AGb9VYCgBScT8uJkfHJqgkFxaV02ogUfrU5HVpQefeNsM6o/bhYldj/huF0g",
	"clSRnEe4BAeFWFVV+bMtaeObsFWtaA7uOP3clj19tSONm98MVr/MTNxiU0fLNQRXPwdsIZuZYwaNF5I9",
	"uKQRWK2qtCgynlr4oy/afS2tRe9dZHdWpU11++hCimrLOxuPu9787VcTobPxad/TS8f1JDDd1zqLbFfV",
	"BWXRe+cXp/P0+XV+ELTEpVT8T5elL8cvnl/pG6nuOGMgnMaXz6/xWmI0l6WwNv70dwRzanZfQbPoFtQK",
	"VOQJY+Iu9s/VcTYzP/kG4MbOYzqAtqW6XclNJ6CRE9PTCNxFMW0s8fuaQdVdtlL/NQ0hcDy1PoYYoD0d",
	"4gkRhPLj/77yH+krb/5hbaUq05ll1pbK1bVbgUZkM9v8FQAA//86t63POCAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
